In [1]:
library(tidyverse)
library(magrittr) # better handling of pipes
library(purrr) # to work with lists and map functions
library(glue) # to paste strings
library(stringr) # to hand strings
library(rvest) # rvest makes scraping easier
library(polite)
library(tidytext)

-- Attaching packages --------------------------------------- tidyverse 1.2.1 --
v ggplot2 3.0.0     v purrr   0.2.5
v tibble  1.4.2     v dplyr   0.7.6
v tidyr   0.8.1     v stringr 1.3.1
v readr   1.1.1     v forcats 0.3.0
-- Conflicts ------------------------------------------ tidyverse_conflicts() --
x dplyr::filter() masks stats::filter()
x dplyr::lag()    masks stats::lag()

Attaching package: 'magrittr'

The following object is masked from 'package:purrr':

    set_names

The following object is masked from 'package:tidyr':

    extract


Attaching package: 'glue'

The following object is masked from 'package:dplyr':

    collapse

Loading required package: xml2

Attaching package: 'rvest'

The following object is masked from 'package:purrr':

    pluck

The following object is masked from 'package:readr':

    guess_encoding

In [2]:
url_titles <- "http://www.who.int/diabetes/facts/world_figures/en/index2.html#" # this is the base url from where the scraping starts
#For reading and parsing our webpage at main_url into R
page_title <- read_html(url_titles)
page_title

{xml_document}
<html>
[1] <head>\n<meta http-equiv="X-UA-Compatible" content="IE=edge">\n<meta http ...
[2] <body class="main-site">\n\n\t\t<!-- begin: page -->\n\t<div id="sf-top-h ...

In [15]:
country_titles<-page_title %>%
  html_nodes("table.tableData") %>%  
 # html_nodes("td") %>% 
  html_table() #Cleaning up the results with html_table
country_titles

#i<-1




#table.tableData

[[1]]
                         X1         X2         X3
1                   Country       2000       2030
2               Afghanistan    468,000  1,403,000
3                   Bahrain     37,000     99,000
4                    Cyprus     50,000     87,000
5                  Djibouti      7,000      9,000
6                     Egypt  2,623,000  6,726,000
7  Islamic Republic of Iran  2,103,000  6,421,000
8                      Iraq    668,000  2,009,000
9                    Jordan    195,000    680,000
10                   Kuwait    104,000    319,000
11                  Lebanon    146,000    378,000
12   Libyan Arab Jamahiriya     88,000    245,000
13                  Morocco    427,000  1,138,000
14                     Oman    113,000    343,000
15                 Pakistan  5,217,000 13,853,000
16                    Qatar     38,000     88,000
17             Saudi Arabia    890,000  2,523,000
18                  Somalia     97,000    331,000
19                    Sudan    447,000  1,277,000
20     Syrian Arab Republic    627,000  2,313,000
21                  Tunisia    166,000    388,000
22     United Arab Emirates    350,000    684,000
23                    Yemen    327,000  1,286,000
24                    Total 15,188,000 42,600,000